version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tucostattoo
      MYSQL_USER: root
      MYSQL_PASSWORD: valentin1770
      MYSQL_ROOT_PASSWORD: valentin1770
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
